version: "3.8"

services:
  database:
    image: postgres:16.0
    user: root
    container_name: challenge-coodesh-squadfy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge-coodesh-squadfy
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - ../../docker/volumes/postgres:/var/lib/postgresql/data
networks:
  dev-network:
    driver: bridge
